package hyundai.softeer.orange.jwt;

import hyundai.softeer.orange.admin.entity.Admin;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.jackson.io.JacksonDeserializer;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import javax.crypto.SecretKey;
import java.util.Calendar;
import java.util.Date;
import java.util.Map;

public class JwtTest {
    // generated by web
    private static final String KEY = "RS1Asd5x0Z0EpKdDmevsc1tJSIZoGNvuxLqL+I35qCM=";
    @Test
    void testJwt() {
        SecretKey key = JWTManager.getDecodedSecretKey(KEY);

        // 시작 시간 설정
        Date issuedDate = new Date();
        // 이슈 시간 설정
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(issuedDate);
        calendar.add(Calendar.SECOND, 5);

        Date expirationDate = calendar.getTime();

        String jws = Jwts.builder()
                .header()
                .type("JWT")
                .and()
                .issuer("team-orange")
                .issuedAt(issuedDate)
                .expiration(expirationDate)
                .signWith(key)

                .subject("admin")
                .claim("user", Admin
                        .builder()
                        .nickname("admin")
                        .password("test")
                        .build()
                )
                .compact();

        var obj = Jwts.parser()
                .verifyWith(key)
                .json(new JacksonDeserializer<>(Map.of("user", Admin.class)))
                .build().parseSignedClaims(jws);
        String sub = obj.getPayload().getSubject();

        // 자체적으로 가진 JsonDeserializer 사용하든지, 아니면 ObjectMapper로 직접 역직렬화하라고 나옴
        Admin admin = obj.getPayload().get("user", Admin.class);

        Assertions.assertThat(admin.getNickname()).isEqualTo("admin");
        Assertions.assertThat(admin.getPassword()).isEqualTo("test");
        Assertions.assertThat(sub).isEqualTo("admin");
    }
}
